### ISSUE TITLE
Recent stock value not retrieved

### ISSUE THREAD

**Issue by m4ding** [Newan/ioBroker.stock-market#1]
Hi,

i have installed version 0.0.2, thanks for developing it! Unfortunately, it doesnt retrieve the actual value of market close. I have configured the adapter as follows:

![3BD3A0B8-EE70-4891-B3A7-ECB73EFD1174](https://user-images.githubusercontent.com/65028008/157599503-216f8afb-161d-4bf1-b7ff-b620f84f056e.jpeg)

i assume, folder 0 keeps the most recent stock values (all others I found are older). The values are as follows:

![D3E096DA-FBD9-40F7-969F-05C1B39D5BC1](https://user-images.githubusercontent.com/65028008/157599625-b63725bf-2bab-45c4-9e0b-8323eb77ed1e.jpeg)

however, the actual value is different (market close in nasdaq already)

![32617D0F-4661-4379-BFB3-9014B748D338](https://user-images.githubusercontent.com/65028008/157599764-0bd328af-41f4-4a4d-ab39-acfafb20c4a4.jpeg)

Can you please check?

**Comment by Newan** [comment]
![image](https://user-images.githubusercontent.com/3693094/161445617-4e99b535-8cd9-4857-adc7-aceeda5cef3d.png)

It seem today it is correct?

**Comment by Newan** [comment]
New Version with new API online
