### ISSUE TITLE
prevent too many requests to alphavantage (500 requests/ day)

### ISSUE THREAD

**Issue by m4ding** [Newan/ioBroker.stock-market#2]
I found out that 500 requests per day are permitted. This would mean that it is only allowed to request every 3mins for an update. As far as I see, alphavantage anyway doesnt support real time data in free mode. 

Is it possible:
- to set for free mode 5 minutes or more and adding some info about 500req/ day max
- there was no information in the module with info logging about the "freeze" since 500req per day were exceeded. It would be good to add this to the log

**Comment by Newan** [comment]
For next release maybe

**Comment by Newan** [comment]
New Version with new API online
